apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-name-based-vs-and-default
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/rewrite-target: /  # no hace falta en este ejemplo.
spec:
  rules:
  - host: api.35-224-162-28.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mi-servicio
            port:
              number: 80