apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-initdb-config1
data:
  create_user.js: |
    db.createUser({
      user: "jean",
      pwd: "123456",
      roles: [
          {
              role: "readWrite",
              db: "petsdb"
          }
      ]
    })