apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-pvc
spec:
  # storageClassName: ""
  accessModes:
    - ReadWriteOnce
  # volumeName: pv
  resources:
    requests:
      storage: 1Gi

# ---

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   namespace: pets
#   name: mongo-data-pv
# spec:
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 1Gi
#   hostPath:
#     path: /data/mongo