apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb1
  labels:
    app-deployment: mongodb1
spec:
  replicas: 1
  selector:
    matchLabels:
      app-pod: mongodb1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app-pod: mongodb1
    spec:
      restartPolicy: Always
      containers:
        - name: mongodb1
          image: mongo
          args:
            - "--dbpath"
            - "/data/db"
          ports:
            - containerPort: 27017
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
          livenessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: password
            - name: MONGO_INITDB_DATABASE
              value: petsdb
          volumeMounts:
            - name: "mongo-data-dir"
              mountPath: "/data/db"
            - name: mongo-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: "mongo-data-dir"
          persistentVolumeClaim:
            claimName: "mongodb-data-pvc1"
        - name: mongo-initdb
          configMap:
            name: mongo-initdb-config1
    