apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-initdb-config
data:
  create_user.js: |
    db.createUser({
      user: "jean",
      pwd: "123456",
      roles: [
          {
              role: "readWrite",
              db: "petsdb"
          }
      ]
    })
    db = db.getSiblingDB("petsdb");
    db.createCollection("dogs")
    db.dogs.insertMany([
      {
        "name": "Rocky",
        "age": "10"
      }
    ])

# ---

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: mongo-initdb-config
# data:
  create_db.js: |
    db.grantRolesToUser(
      "jean",
      [
        {
            role: "readWrite",
            db: "petsdb"
        }
      ] 
    )