version: '3.7'
services:
  app:
    container_name: app
    build:
      context: app
      target: prod
    restart: always
    ports:
      - ${APP_PORT}:8080
    depends_on:
      - mongodb
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        labels: "app_production_status"
        env: "os"
  
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      PUID: 1000
      PGID: 1000
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
      - 27019:27019
    expose:
      - ${DB_PORT}
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongodb:/data/db
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        labels: "mongo_production_status"
        env: "os"

volumes:
  mongodb: