apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "petsclinic.fullname" . }}
data:
  DB_HOST: {{ .Values.configmap.DB_HOST | quote }}
  DB_PORT: {{ .Values.configmap.DB_PORT | quote }}
  DB_NAME: {{ .Values.configmap.DB_NAME | quote }}
  DB_USER: {{ .Values.configmap.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.configmap.DB_PASSWORD | quote }} 